name: CI (conda)
on: [push]

jobs:
  build:
    strategy:
      matrix:
        #os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        os: ['ubuntu-latest']
        #python-version: [3.7, 3.8]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: fingernat
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          environment-file: env/fingeRNAt_env.yml
      - name: run test
        run: |
          cd tests
          conda env list
          source activate fingernat
          conda env list
          conda list
          python fingeRNAt_test.py
